name: ntdntf
favicon: null
layout_spectrum: 0
typography_spectrum: 0.34277
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c33f93'
    - '#127bb9'
    - '#fec530'
    - '#ad861e'
  brandStrength: 0.75
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
