name: ntdntf
favicon: null
layout_spectrum: 0.580255082808435
typography_spectrum: 0.9176111954730004
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5334028855431825
  lightness: 0.48129639821127057
  saturation: 0.8545754349324852
  rhythmicContrast: 0.0021216918248683214
purpose: []
